### ISSUE TITLE
TreeMapSpreadsheetCellBox.cellBox need to handle/abort to avoid overflowing column/rows

### ISSUE THREAD

**Issue by mP1** [mP1/walkingkooka-spreadsheet#1105]
```
java.lang.IllegalArgumentException: Invalid column value 16384 expected between 0 and 16384
	at walkingkooka.spreadsheet.reference.SpreadsheetColumnReference.checkValue(SpreadsheetColumnReference.java:93)
	at walkingkooka.spreadsheet.reference.SpreadsheetColumnReference.setValue(SpreadsheetColumnReference.java:85)
	at walkingkooka.spreadsheet.reference.SpreadsheetColumnReference.setValue(SpreadsheetColumnReference.java:27)
	at walkingkooka.spreadsheet.reference.SpreadsheetColumnOrRowReference.add0(SpreadsheetColumnOrRowReference.java:148)
	at walkingkooka.spreadsheet.reference.SpreadsheetColumnReference.add(SpreadsheetColumnReference.java:77)
	at walkingkooka.spreadsheet.store.TreeMapSpreadsheetCellStore.cellBox(TreeMapSpreadsheetCellStore.java:214)
	at walkingkooka.spreadsheet.engine.BasicSpreadsheetEngine.cellBox(BasicSpreadsheetEngine.java:568)
```

**Comment by mP1** [comment]
- Closed by https://github.com/mP1/walkingkooka-spreadsheet/pull/1090
